services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.31.0-alpine3.23-slim
    user: "1984:1984"
    volumes:
      - ./docker/configs/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/configs/nginx-chadmin.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - php-sock:/sock
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - frontend
    env_file:
      - .env
    networks:
      - docker-net

  php-fpm:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: base
    user: "1984:1984"
    volumes:
      - .:/var/www/html
      - php-sock:/sock
    env_file:
      - .env
    networks:
      - docker-net

  composer:
    image: composer:2.9.8
    user: "1984:1984"
    volumes:
      - .:/app
    working_dir: /app
    command: ["composer", "install", "--no-interaction", "--prefer-dist"]
    networks:
      - docker-net

  frontend:
    image: node:24.15.0-alpine3.23
    user: "1984:1984"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install"
    networks:
      - docker-net

volumes:
  php-sock:

networks:
  docker-net:
    driver: "bridge"
