#index:
#    path: /
#    controller: App\Controller\DefaultController::index

htmx_root:
    path: /
    controller: App\Controller\HtmxController::index

# API Маршрути для QueriesController залишаються такими ж
